### ISSUE TITLE
How to remove the front line ?

### ISSUE THREAD

**Issue by agileago** [fungku/colour-schemes#1]
![image](https://cloud.githubusercontent.com/assets/11799110/10122030/7c318f18-653b-11e5-97a8-30a0de857966.png)

Do you know how to set up to remove the red arrow line in the Jetbrains editor ?

i see your screenshot that dose not has the line

**Comment by ryanwinchester** [comment]
I think it is `Editor > General > Code Folding` and `Editor > General > Appearance > Show vertical indent guides`

**Comment by agileago** [comment]
yeah.Great! it is ok! thanks
